apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manager-app-{{ name }}-destination-rule
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: web-static
spec:
  host: {{ host }}
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: SIMPLE
          sni: {{ host }}
  exportTo:
    - "."
    - istio-system