def DEPLOY_GIT_SCOPE
def DEPLOY_NAMESPACE
def WEB_SERVER_HOST
def API_HOST
def REGISTRY_HOST
def JINJA2_VARS_FILE_PATH
def ESCAPED_JOB_NAME
def MARKDOWN_ESCAPE_CHARS = ['_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!'] as Set

def generateExtHttp(name, host, extHttpsPort, varsPath, useMtls) {
    sh "jinja2 -D name=$name -D host=$host -Dext_https_port=$extHttpsPort distrib/templates/ext-http/service-entry.yaml $varsPath > distrib/${name}-service-entry.yaml"
    sh "jinja2 -D name=$name -D host=$host -Dext_https_port=$extHttpsPort distrib/templates/ext-http/virtual-service.yaml $varsPath > distrib/${name}-virtual-service.yaml"
    if (useMtls) {
        sh "jinja2 -D name=$name -D host=$host -Dext_https_port=$extHttpsPort distrib/templates/ext-http/destination-rule-mtls.yaml $varsPath > distrib/${name}-destination-rule.yaml"
    } else {
        sh "jinja2 -D name=$name -D host=$host -Dext_https_port=$extHttpsPort distrib/templates/ext-http/destination-rule.yaml $varsPath > distrib/${name}-destination-rule.yaml"
    }
    sh "jinja2 -D name=$name -D host=$host -Dext_https_port=$extHttpsPort distrib/templates/ext-http/service.yaml $varsPath > distrib/${name}-service.yaml"

    return "-f distrib/${name}-service.yaml " +
            "-f distrib/${name}-service-entry.yaml " +
            "-f distrib/${name}-virtual-service.yaml " +
            "-f distrib/${name}-destination-rule.yaml "
}

def generateImageTag(container) {
    def scope = sh(encoding: 'UTF-8', returnStdout: true, script: 'git name-rev --name-only HEAD')
            .trim()
            .tokenize('/')
            .last()
            .toLowerCase()

    return 'pro.ra-tech/garden-manager/' + scope + '/' + container + ':latest'
}

static def removeProtocol(url) {
    return url.substring('https://'.length())
}

def escapeMd(input, escapeChars) {
    def builder = new StringBuilder()

    input.each { ch ->
        if (escapeChars.contains(ch)) {
            builder.append('\\')
        }
        builder.append(ch)
    }

    return builder.toString()
}

pipeline {
    agent { label 'jenkins-agent1' }

    parameters {
        string(name: 'web_server_image', description: 'Web server with static image tag')
    }

    stages {
        stage('Determine git scope') {
            steps {
                script {
                    ESCAPED_JOB_NAME = escapeMd(JOB_NAME, MARKDOWN_ESCAPE_CHARS)
                    raTechNotify(message: "🚀 Job *${ESCAPED_JOB_NAME}* started [BUILD](${BUILD_URL}) 🚀", markdown: true)

                    DEPLOY_GIT_SCOPE = BRANCH_NAME.tokenize('/').last().toLowerCase()
                    echo "Git branch scope: '${DEPLOY_GIT_SCOPE}'"
                }
            }
        }

        stage('Determine stand specific params') {
            steps {
                script {
                    if (BRANCH_NAME.startsWith('release/')) {
                        DEPLOY_NAMESPACE = 'garden-manager-app'
                        WEB_SERVER_HOST = 'garden-manager.cloud.ra-tech.pro'
                        API_HOST = 'api.garden-manager.cloud.ra-tech.pro'
                        REGISTRY_HOST = removeProtocol(DOCKER_REGISTRY_HOST)
                        JINJA2_VARS_FILE_PATH = 'distrib/deploy/vars.yaml'
                    } else {
                        DEPLOY_NAMESPACE = 'garden-manager-app-test'
                        WEB_SERVER_HOST = 'garden-manager.test.cloud.ra-tech.pro'
                        API_HOST = 'api.garden-manager.test.cloud.ra-tech.pro'
                        REGISTRY_HOST = removeProtocol(SNAPSHOTS_DOCKER_REGISTRY_HOST)
                        JINJA2_VARS_FILE_PATH = 'distrib/deploy/test-vars.yaml'
                    }

                    println "Namespace to deploy web server: $DEPLOY_NAMESPACE"
                    println "Web server host: $WEB_SERVER_HOST"
                }
            }
        }

        stage('Cleanup k8s namespace') {
            steps {
                script {
                    def namespace = DEPLOY_NAMESPACE
                    withKubeConfig([credentialsId: 'jenkins-k8s-cert', serverUrl: KUBERNETES_API_URL, namespace: namespace]) {
                        sh 'kubectl version'

                        println 'Deleting web static deployment and pods'
                        sh "kubectl delete deployment -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl wait --for=delete pod -l app=garden-manager-app --timeout 5m -n $namespace"

                        println 'Deleting other web static manifests'
                        sh "kubectl delete service -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl delete virtualservice -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl delete destinationrule -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl delete gateway -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl delete networkpolicy -l app.kubernetes.io/component=web-static -n $namespace"
                        sh "kubectl delete configmap -l app.kubernetes.io/component=core -n $namespace"
                        sh "kubectl delete serviceentry -l app.kubernetes.io/component=web-static -n $namespace"

                        println "Deleting istio components"
                        sh "kubectl delete deployment -l app.kubernetes.io/component=istio-egressgw -n $namespace"
                        sh "kubectl wait --for=delete pod -l app=garden-manager-app-egressgw -n $namespace"
                        sh "kubectl delete service -l app.kubernetes.io/component=istio-egressgw -n $namespace"
                        sh "kubectl delete role -l app.kubernetes.io/component=istio-egressgw -n $namespace"
                        sh "kubectl delete rolebinding -l app.kubernetes.io/component=istio-egressgw -n $namespace"
                        sh "kubectl delete serviceaccount -l app.kubernetes.io/component=istio-egressgw -n $namespace"
                        sh "kubectl delete networkpolicy -l app.kubernetes.io/component=istio -n $namespace"

                        println 'Cleanup finished'
                    }
                }
            }
        }

        stage('Deploy to k8s') {
            steps {
                script {
                    def varsPath = JINJA2_VARS_FILE_PATH
                    def namespace = DEPLOY_NAMESPACE
                    def host = WEB_SERVER_HOST
                    def apiHost = API_HOST
                    def imageTag = params.web_server_image
                            ? params.web_server_image
                            : generateImageTag('garden-manager-app')
                    def apiApply

                    withPythonEnv('Python-3') {
                        sh 'pip install -U jinja2-cli'

                        // Istio egress gateway
                        sh "jinja2 distrib/templates/istio/egressgw-deployment.yaml $varsPath > distrib/egressgw-deployment.yaml"
                        sh "jinja2 distrib/templates/istio/egressgw-service.yaml $varsPath > distrib/egressgw-service.yaml"
                        sh "jinja2 distrib/templates/network-policy-egress.yaml $varsPath > distrib/network-policy-egress.yaml"
                        sh "jinja2 distrib/templates/istio/egressgw-service-account.yaml $varsPath > distrib/egressgw-service-account.yaml"
                        sh "jinja2 distrib/templates/istio/egressgw-role.yaml $varsPath > distrib/egressgw-role.yaml"
                        sh "jinja2 distrib/templates/istio/egressgw-role-binding.yaml $varsPath > distrib/egressgw-role-binding.yaml"
                        sh "jinja2 distrib/templates/configmaps/egress-vault-agent.yaml $varsPath > distrib/egress-vault-agent.yaml"

                        // web static
                        sh "jinja2 -D image_tag=$imageTag distrib/templates/deployment.yaml $varsPath > distrib/deployment.yaml"
                        sh "jinja2 distrib/templates/service.yaml $varsPath > distrib/service.yaml"
                        sh "jinja2 distrib/templates/network-policy-restricted.yaml $varsPath > distrib/network-policy-restricted.yaml"
                        sh "jinja2 distrib/templates/ingress-gateway.yaml $varsPath > distrib/ingress-gateway.yaml"
                        sh "jinja2 distrib/templates/egress-gateway.yaml $varsPath > distrib/egress-gateway.yaml"
                        sh "jinja2 distrib/templates/destination-rule.yaml $varsPath > distrib/destination-rule.yaml"
                        sh "jinja2 distrib/templates/virtual-service.yaml $varsPath > distrib/virtual-service.yaml"
                        sh "jinja2 distrib/templates/egw-destination-rule.yaml $varsPath > distrib/egw-destination-rule.yaml"

                        // API
                        apiApply = generateExtHttp('api', apiHost, 443, varsPath, true)
                    }

                    withKubeConfig([credentialsId: 'jenkins-k8s-cert', serverUrl: KUBERNETES_API_URL, namespace: namespace]) {
                        println "Applying istio egress gateway manifests"
                        sh 'kubectl apply ' +
                                '-f distrib/network-policy-egress.yaml ' +
                                '-f distrib/egress-vault-agent.yaml ' +
                                '-f distrib/egressgw-service.yaml ' +
                                '-f distrib/egressgw-service-account.yaml ' +
                                '-f distrib/egressgw-role.yaml ' +
                                '-f distrib/egressgw-role-binding.yaml ' +
                                '-f distrib/egressgw-deployment.yaml'

                        sleep time: 3, unit: 'SECONDS'
                        sh "kubectl wait --for=condition=ready --timeout=5m -n $namespace pods -l app=garden-manager-app-egressgw"

                        println 'Applying web static manifests'
                        sh 'kubectl apply ' +
                                '-f distrib/network-policy-restricted.yaml ' +
                                '-f distrib/service.yaml ' +
                                '-f distrib/ingress-gateway.yaml ' +
                                '-f distrib/egress-gateway.yaml ' +
                                '-f distrib/virtual-service.yaml ' +
                                '-f distrib/destination-rule.yaml ' +
                                '-f distrib/egw-destination-rule.yaml ' +
                                apiApply

                        println 'Deploying web static'
                        sh 'kubectl apply -f distrib/deployment.yaml'
                        sleep time: 3, unit: 'SECONDS'
                        sh "kubectl wait --for=condition=ready --timeout=5m -n $namespace pods -l app=garden-manager-app"

                        println 'Deployment finished'
                    }
                }
            }
        }
    }
    post {
            success {
                script{
                    raTechNotify(message: "✅ Job *${ESCAPED_JOB_NAME}* completed successfully [BUILD](${BUILD_URL}) ✅", markdown: true)
                }
            }
            failure {
                script {
                    raTechNotify(message: "❌ Job *${ESCAPED_JOB_NAME}* failed [BUILD](${BUILD_URL}) ❌", markdown: true)
                }
            }
            aborted {
                script {
                    raTechNotify(message: "✋ Job *${ESCAPED_JOB_NAME}* aborted [BUILD](${BUILD_URL}) ✋", markdown: true)
                }
            }
        }
}