host: garden-manager.test.cloud.ra-tech.pro
api_host: api.garden-manager.test.cloud.ra-tech.pro
namespace: garden-manager-app-test
registry: snapshots.docker-registry.ra-tech.pro

egress:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
  vault:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 64Mi

web_static:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
  istio:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

vault:
  tls_url: https://vault.ra-tech.pro
  host: vault.ra-tech.pro