apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-manager-app
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manger-app
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: web-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garden-manager-app
      app.kubernetes.io/name: garden-manager-app
      app.kubernetes.io/component: web-static
      app.kubernetes.io/part-of: garden-manager
      app.network.policy: restricted
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: garden-manager-app
        app.kubernetes.io/name: garden-manager-app
        app.kubernetes.io/component: web-static
        app.kubernetes.io/part-of: garden-manager
        app.network.policy: restricted
        sidecar.istio.io/proxyCPU: {{ core.istio.requests.cpu }}
        sidecar.istio.io/proxyCPULimit: {{ core.istio.limits.cpu }}
        sidecar.istio.io/proxyMemory: {{ core.istio.requests.memory }}
        sidecar.istio.io/proxyMemoryLimit: {{ core.istio.limits.memory }}
    spec:
      containers:
        - name: garden-manager-app
          image: {{ registry }}/{{ image_tag }}
          ports:
            - containerPort: 8080
              name: web-static
            - containerPort: 8081
              name: health
          readinessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              cpu: {{ web_static.requests.cpu }}
              memory: {{ web_static.requests.memory }}
            limits:
              cpu: {{ web_static.limits.cpu }}
              memory: {{ web_static.limits.memory }}
      imagePullSecrets:
        - name: docker-registry-creds