apiVersion: v1
kind: Service
metadata:
  name: garden-manager-app-service
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manager-app-service
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: web-static
spec:
  selector:
    app: garden-manager-app
  ports:
    - name: web-static
      protocol: TCP
      port: 8080
      targetPort: web-static
    - name: health
      protocol: TCP
      port: 8081
      targetPort: health
