apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: garden-manager-app-rule
  namespace: {{ namespace }}
  labels:
    app.kubernetes.io/name: garden-manager-app-rule
    app.kubernetes.io/part-of: garden-manager
    app.kubernetes.io/component: web-static
spec:
  exportTo:
    - "."
    - istio-system
  hosts:
    - {{ host }}
  gateways:
    - "{{ namespace }}/garden-manager-app-ingress-gateway"
    - mesh
  http:
    - name: web-server-route
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: garden-manager-app-service.{{ namespace }}.svc.cluster.local
            port:
              number: 8080