apiVersion: v1
kind: ServiceAccount
metadata:
  name: garden-manager-app-egressgw-service-account
  namespace: {{ namespace }}
  labels:
    app: garden-manager-app-egressgw
    app.kubernetes.io/name: garden-manager-app-egressgw
    app.kubernetes.io/component: istio-egressgw
    app.kubernetes.io/part-of: garden-manager-app
    istio.io/rev: 1-18-2